# Netlify toml Configuration File
# Notes
# - Install the "Even Better TOML" Visual Studio Code addon to get color syntax highlighting

[build.environment]
  FAVORITE_COLORT = "green"

# THESE ONLY WORK IN NETLIFY? THE REDIRECTS IN next.config.mjs work on localhost/not on Netlify.
[[redirects]]
  from = "/geoalt" 
  to = "/geolocation"
  status = 200


# NOTE: You need this plugin because Netlify requires an index.html and next.js doesn't have one. This will result in a 404.
[[plugins]]
  package = "@netlify/plugin-nextjs"
